version: "3"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: gen-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_generator
    ports:
      - "35432:5432"
  localstack:
    image: localstack/localstack:3.0.1-arm64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kms,sqs,s3
      - DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack/aws-configure.sh:/etc/localstack/init/ready.d/aws-configure.sh
      - ./localstack/init-kms.sh:/etc/localstack/init/ready.d/init-kms.sh
      - ./localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh
      - ./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
      - ./localstack/config/cors.json:/etc/localstack/config/cors.json

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  clamav:
    build:
      context: ./antivirus
    ports:
      - "3310:3310"
    volumes:
      - ./antivirus/config/supervisor.conf:/etc/supervisor/conf.d/supervisord.conf
      - clamav-db:/var/lib/clamav
    container_name: clamav-container
    command: bash -c "freshclam && /usr/bin/supervisord -n"
    restart: always

volumes:
  clamav-db:
