version: "3"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: test-generator-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_generator
    ports:
      - "35432:5432"
  localstack:
    image: localstack/localstack:3.0.1-arm64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kms,sqs,s3
    volumes:
      - ./localstack/init-kms.sh:/etc/localstack/init/ready.d/init-kms.sh
      - ./localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh
      - ./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
#      - ./storage:/etc/localstack/init/ready.d
