version: "3"
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: test-generator-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_generator
    ports:
      - "35432:5432"