server:
  port: ${SERVER_PORT}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 30MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate.dialect: ${JPA_HIBERNATE_DIALECT}

file-upload:
  allowed-extensions: ${FILE_UPLOAD_ALLOWED_EXTENSIONS}

security:
  secret: ${SECURITY_SECRET}
  refresh-secret: ${SECURITY_REFRESH_SECRET}
  allowed-origin: ${SECURITY_ALLOWED_ORIGIN}
  refresh-db-secret: ${SECURITY_REFRESH_DB_SECRET}

csrf:
  cookie_domain: ${CSRF_COOKIE_DOMAIN}

aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  queue-name: ${AWS_QUEUE_NAME}
  s3-bucket: ${AWS_S3_BUCKET}
  url: ${AWS_URL}
  sqs-url: ${AWS_SQS_URL}

generation:
  key: ${GENERATE_TEST_SECRET}
  models:
    question: ${GENERATION_MODELS_QUESTION}
    answers: ${GENERATION_MODELS_ANSWERS}

retry:
  attempt: ${RETRY_ATTEMPT}

logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE}
