name: STAGE - Deploy to Elastic Beanstalk

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Deploy branch'
        required: true
        default: 'develop'
      version_label:
        description: 'Deploy branch'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./generation-service

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.event.inputs.version_label }}
          zip_file: target/*.jar
